# Generated by Django 6.0.1 on 2026-02-01 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da disciplina')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga horária (horas)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('professor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas_responsavel', to='accounts.professor', verbose_name='Professor responsável')),
                ('usuario_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário administrador responsável pelo cadastro')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_turma', models.CharField(max_length=45, unique=True, verbose_name='Código da turma')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('periodo', models.CharField(max_length=20, verbose_name='Período/Série')),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('INTEGRAL', 'Integral')], max_length=20, verbose_name='Turno')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('usuario_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário administrador responsável pelo cadastro')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['curso', 'codigo_turma'],
            },
        ),
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado')], max_length=3, verbose_name='Dia da semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de término')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.disciplina', verbose_name='Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.professor', verbose_name='Professor')),
                ('usuario_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário administrador responsável pelo cadastro')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Horário de aula',
                'verbose_name_plural': 'Horários de aula',
                'ordering': ['turma', 'dia_semana', 'hora_inicio'],
            },
        ),
    ]
