# Generated by Django 6.0.1 on 2026-02-01 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_siape', models.CharField(max_length=20, unique=True, verbose_name='Matrícula SIAPE')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('coordenacao', models.CharField(max_length=100, verbose_name='Coordenação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do sistema')),
                ('usuario_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professores_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário administrador responsável pelo cadastro')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
