# Generated by Django 6.0.1 on 2026-02-01 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField(verbose_name='Data da aula a ser permutada')),
                ('motivo', models.TextField(verbose_name='Motivo da permuta')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status da solicitação')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora da solicitação')),
                ('data_decisao', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora da decisão')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.horarioaula', verbose_name='Horário de aula')),
                ('professor_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permutas_solicitadas', to='accounts.professor', verbose_name='Professor solicitante')),
                ('professor_substituto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permutas_como_substituto', to='accounts.professor', verbose_name='Professor substituto')),
                ('usuario_decisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permutas_decididas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que decidiu a permuta')),
            ],
            options={
                'verbose_name': 'Permuta',
                'verbose_name_plural': 'Permutas',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Reposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reposicao', models.DateField(verbose_name='Data da reposição')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('permuta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reposicao', to='permuta.permuta', verbose_name='Permuta relacionada')),
            ],
            options={
                'verbose_name': 'Reposição',
                'verbose_name_plural': 'Reposições',
                'ordering': ['-data_reposicao'],
            },
        ),
    ]
